name: x_printer_pck


description: Flutter plugin for iOS Bluetooth thermal printer integration
version: 0.0.1
homepage: https://github.com/eq-devs/x_printer_pck
repository: https://github.com/eq-devs/x_printer_pck
issue_tracker: https://github.com/eq-devs/x_printer_pck/issues



environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 
flutter: 
  plugin:
    platforms:
      ios:
        pluginClass: XPrinterPckPlugin
 